# Generated by Django 2.1 on 2018-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180806_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default='open tweet'),
            preserve_default=False,
        ),
    ]
